[package]
name = "kwap-msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["alloc"]
alloc = ["no_std"]
no_std = []
test = []
docs = []

[dependencies]
coap-lite = "0.7"
arrayvec = "0.7"
