name: 'kwap_macros(bump)'

on:
  push:
    branches: [ 'main' ]
    path: ['kwap_macros']

jobs:
  kwap_macros__bump:
    if: |
         !startsWith(github.event.head_commit.message, 'bump')
         && !startsWith(github.event.head_commit.message, 'ci')
         && !startsWith(github.event.head_commit.message, 'chore')
         && !startsWith(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    # run `standard-version`
    # - update CHANGELOG,
    # - create version tag
    # - create version commits
    - run: |
        npx standard-version \
          --tag-prefix kwap_macros@ \
          --releaseCommitMessageFormat 'chore(release): kwap_macros@{{currentTag}}'
      working-directory: 'kwap_macros'

    - name: 'update Cargo.lock'
      run: 'cargo check'

    - run: 'git add -A; git commit --amend --no-edit'

    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 'git push'

    # triggers kwap_macros(publish)
    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 'git push --tags'
